### ISSUE TITLE
Memory is not released when using ply

### ISSUE THREAD

**Issue by XPYYWH** [connormanning/entwine#236] opened 2020-08-26 11:04 UTC
I want to slice PLY data instead of LAZ point cloud data, so I apply the process of processing laz data to processing ply data, including point cloud data boundaries, number of points, coordinate information, etc. The result is no problem. But the memory occupied by data processing will not be released until the main function ends. Laz data will release the memory at the end of data processing. What is the reason?
<img width="702" alt="ply" src="https://user-images.githubusercontent.com/66302327/91296538-5d6ea400-e7cf-11ea-9a59-f505cc3bb5fa.png">
I sleep for 30 seconds before the main function ends. The memory is always occupied. When I process the laz data in the same process, it will be released before the main function ends.
<img width="695" alt="laz" src="https://user-images.githubusercontent.com/66302327/91296961-1339f280-e7d0-11ea-9e68-6aa50b06784d.png">

**Comment by connormanning** [comment] 2020-08-28 15:25
I'm not sure, but Entwine simply executes a [PDAL](https://pdal.io) pipeline to read input data.  So if the behavior of different file types for similar data is drastically different, then I'd start by looking at the specific PDAL reader invoked.  In this case, it would be the [PLY reader](https://pdal.io/stages/readers.ply.html).

From a quick glance at the code there, I see that the LAS reader cleans up some resources when it is done [here](https://github.com/PDAL/PDAL/blob/master/io/LasReader.cpp#L968).  The PLY reader has a similar cleanup method [here](https://github.com/PDAL/PDAL/blob/master/io/PlyReader.cpp#L466), but this only cleans up the filehandle - so maybe the fact that [`m_elements`](https://github.com/PDAL/PDAL/blob/master/io/PlyReader.hpp#L126) is not cleared during `done` is the cause of what you're seeing.

**Comment by connormanning** [comment] 2020-08-28 15:29
I've opened an issue on the PDAL repo for you @XPYYWH: pdal/pdal#3224.  If it's determined that this is caused by something Entwine is doing, I'll take another look.  Closing for now.

**Closed by connormanning** 2020-08-28 15:29 UTC

**Comment by XPYYWH** [comment] 2020-08-31 05:53
OK,thanks.
