### ISSUE TITLE
performance benchmark or estimate

### ISSUE THREAD

**Issue by mikeskaug** [connormanning/entwine#39] opened 2017-05-08 16:19 UTC
Thanks for the great tool!

I finally finished indexing and visualizing a set of data only to discover that (I think) all of the 14 million points were collapsed onto two lat/lon positions because I was using an incorrect scale factor (X=-45.94672 -> X=-45).

Indexing ~14 million points took ~48 hours on my laptop:
```
docker run -it -v ~/point-cloud-vis:$HOME connormanning/entwine build -i ~/csv/ -o ~/entwine/Jakobshavn -r EPSG:4326 EPSG:3857
```

I was wondering if that is the expected performance? I could certainly use a smaller subset while developing to increase the iteration speed, but it might also be useful to have some examples or estimates in the documentation about the time to index 1,000,000 points etc.

**Comment by connormanning** [comment] 2017-05-09 07:51
Seems like something is going wrong - on my MacBook, it takes about 45 seconds to index 15M points. You might try it without reprojection and see how that goes. If you can provide a link to the dataset I can take a look next week.

**Comment by connormanning** [comment] 2017-05-22 19:09
I think this is a data issue - so I'll close this for now since I can't reproduce without the data.  In lieu of any formal benchmarks at the moment, I'll dump some of my build experience here.

At cloud scale: Ubuntu 16.04 c3.8xlarge EC2 instance with 30 cores/60GB RAM via Docker, indexing pace (with reprojection) is about 2.6 billion points per hour using 28 threads, and typically uses well under 30GB RAM.  This scales down somewhat linearly, e.g. on a c3.4xlarge with half those specs using ~14 threads, indexing pace and RAM usage approximately halves as well.

At desktop scale: this will of course vary wildly depending on your computer.  For some rough estimates from my 2013 MacBook Pro with default settings, I can index 10M points in a single file in about 30 seconds.  For datasets with many files, I just did a 150M point terrestrial dataset in about 8 minutes.

**Closed by connormanning** 2017-05-22 19:09 UTC

**Comment by nicolas-chaulet** [comment] 2019-01-29 15:54
> At cloud scale: Ubuntu 16.04 c3.8xlarge EC2 instance with 30 cores/60GB RAM via Docker, indexing pace (with reprojection) is about 2.6 billion points per hour using 28 threads, and typically uses well under 30GB RAM. This scales down somewhat linearly, e.g. on a c3.4xlarge with half those specs using ~14 threads, indexing pace and RAM usage approximately halves as well.

I am curious to know what setting you have used to achieve this speed. Even on Desktop, building an index hardly uses more than 1CPU which makes me think that writing and reading operations are the bottleneck. But you seem to mention that you managed to leverage big amazon instances efficiently? Including writing to s3 I assume.

**Comment by connormanning** [comment] 2019-01-29 16:02
Entwine's multi-threading happens on a per-input-file basis, so parallelization gains only start happening when you have lots of input files.  I typically use the default settings with the `threads` parameter set to the number of cores on the machine (or slightly below).

**Comment by nicolas-chaulet** [comment] 2019-01-29 16:06
Thanks @connormanning that's interesting. Would chunking a big file into smaller files (using pdal for example) and index afterwards be a winning strategy in your opinion? Alternatively do you think there is a way to get parallelization with a single file? Happy to dig in if you think that's doable.

**Comment by connormanning** [comment] 2019-01-29 16:16
There are probably ways to improve single-file performance but it's never warranted much research since the large aerial datasets entwine was tuned around are delivered as lots of files.  So, a lot of what I'd have to say would just be guessing at this point since it hasn't ever been a priority.

If you have a specific problem statement in mind for which you're looking to develop a workflow, send me an email and we can discuss further.
